import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'dev-dist/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      '.kilo/**',
      // Generated by `npm run db:types`. Linting it would report on the Supabase
      // CLI's output style, which is not ours to change.
      'types/database.ts',
    ],
  },

  js.configs.recommended,
  tseslint.configs.recommended,
  reactHooks.configs.flat['recommended-latest'],

  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.es2022 },
    },
    plugins: { 'react-refresh': reactRefresh },
    rules: {
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // Underscore-prefixed args are the escape hatch for required-but-unused
      // callback parameters.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],

      /*
       * `any` appears throughout services/geminiService.ts and the overlays that
       * talk to Gemini directly, because the SDK's grounding-metadata and
       * operation types are loosely specified. Plan step 4 rewrites those call
       * sites behind typed /api contracts, which is the right time to clear this.
       * Warn now so the count is visible and cannot grow silently.
       */
      '@typescript-eslint/no-explicit-any': 'warn',

      // Genuine correctness rules, kept as errors.
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
    },
  },

  // Node-side files: build config, scripts, and Playwright specs.
  {
    files: ['*.config.{ts,js,mjs}', 'scripts/**/*.mjs', 'e2e/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      'no-console': 'off',
    },
  },

  /*
   * Vercel serverless functions. Node globals, no browser globals — the DOM is
   * removed from the type system too, in tsconfig.api.json.
   */
  {
    files: ['api/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      /*
       * `config/env.ts` reads a value that vite.config.ts inlines into the client
       * bundle. A server function importing anything from `config/` pulls browser
       * assumptions — and eventually a browser-inlined secret — into a Node
       * runtime. `api/_lib/env.ts` is the server-side counterpart and duplicates
       * the small amount of shared shape on purpose.
       */
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/config/*', '**/config/**', '@/config/*', '@/config/**'],
              message:
                'Server code must not import from config/ (browser module). Use api/_lib/env.ts.',
            },
          ],
        },
      ],
    },
  },

  /*
   * The same wall from the other side, and the more dangerous direction: a client
   * import of api/_lib pulls `SUPABASE_SERVICE_ROLE_KEY` into the browser bundle.
   * scripts/verify-bundle.mjs is the backstop that catches it if this rule is ever
   * disabled; this is the part that catches it before the build.
   */
  {
    files: [
      'index.tsx',
      'App.tsx',
      'components/**/*.{ts,tsx}',
      'services/**/*.ts',
      'config/**/*.ts',
    ],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/api/_lib/*', '**/api/_lib/**', '@/api/*', '@/api/**'],
              message:
                'Client code must not import from api/_lib — it reads server-only secrets. Call the /api endpoint over HTTP instead.',
            },
          ],
        },
      ],
    },
  },

  // Vitest specs run in jsdom but use Node globals for setup.
  {
    files: ['tests/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
);
